<?php
/**
 * Assets Loader Class
 *
 * @package WpThemeKit
 */

namespace ThemeKit;

// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Handles the registration and enqueuing of scripts and styles.
 */
class Assets_Loader {

	/**
	 * Registers hooks for enqueuing assets and adding the FOUC script.
	 */
	public function __construct() {
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_frontend_assets' ) );
		add_action( 'enqueue_block_editor_assets', array( $this, 'enqueue_editor_assets' ) );
		add_action( 'wp_head', array( $this, 'add_fouc_prevention_script' ), 0 );
	}

	/**
	 * Enqueues scripts and styles for the frontend, using the asset file
	 * generated by @wordpress/scripts for dependencies and versioning.
	 */
	public function enqueue_frontend_assets() {
		$asset_file = plugin_dir_path( __DIR__ ) . 'build/view.asset.php';
		if ( file_exists( $asset_file ) ) {
			$asset = require $asset_file;

			wp_enqueue_style(
				'theme-kit-style',
				plugins_url( '../build/view.css', __FILE__ ),
				array(),
				$asset['version']
			);

			wp_enqueue_script(
				'theme-kit-view-script',
				plugins_url( '../build/view.js', __FILE__ ),
				$asset['dependencies'],
				$asset['version'],
				true
			);
		}
	}

	/**
	 * Enqueues scripts and styles for the block editor.
	 */
	public function enqueue_editor_assets() {
		$asset_file = plugin_dir_path( __DIR__ ) . 'build/index.asset.php';
		if ( file_exists( $asset_file ) ) {
			$asset = require $asset_file;

			wp_enqueue_style(
				'theme-kit-editor-style',
				plugins_url( '../build/index.css', __FILE__ ),
				array( 'wp-edit-components' ),
				$asset['version']
			);

			wp_enqueue_script(
				'theme-kit-editor-script',
				plugins_url( '../build/index.js', __FILE__ ),
				$asset['dependencies'],
				$asset['version'],
				true
			);
		}
	}

	/**
	 * Adds the inline script to the <head> to prevent FOUC by setting
	 * the data-theme attribute before the page content renders.
	 */
	public function add_fouc_prevention_script() {
		$script = "(function(){const pref=localStorage.getItem('theme-preference')||'auto';const isDark=pref==='dark'||(pref==='auto'&&window.matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.setAttribute('data-theme',isDark?'dark':'light');})();";
		printf( '<script id="wp-theme-kit-fouc-prevention">%s</script>', $script ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	}
}
